name: publish yadda yadda

on:
  push:
    branches:
      - master

jobs:
  publish-demo-project-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Demo Project image
        run: |
          docker build . --tag ghcr.io/ashikka/demo-project
      - name: Push Demo Project image
        run: |
          docker push ghcr.io/ashikka/demo-project
